services:
  - postgresql

before_script:
  - psql -c 'create database aiyeplay_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

language: ruby
rvm:
  - 2.7.0
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle install --jobs=3 --retry=3
  - bundle exec rspec
